### ISSUE TITLE
Time values still don't pad with zeroes in .csv file

### ISSUE THREAD

**Issue by aaronbeekay** [BuckeyeCurrent/DynLocV_Logging_Script#2]
When the system time is an integer second (e.g., 23:53:36), the script does not write the decimal portion of the time (.000000).
## Expected behavior:

Logfile writes the full time in the first column of each CSV log:
`YYYY-MM-DD HH:MM:SS.FFFFFF`
where FFFFFF is the fractional seconds in the system time, even when FFFFFF = 000000.
## Observed behavior:

When FFFFFF = 000000, the script writes
`YYYY-MM-DD HH:MM:SS`

**Comment by SoMuchHat** [comment]
Will look into why this still isn't working this morning.
